name: check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 29.4
        ignore_warnings:
          - true
    steps:
    - uses: actions/checkout@v4

    - name: Install vterm system dependencies
      run: sudo apt-get update && sudo apt-get install -y libvterm-dev
      
    - name: Prepare Emacs config
      run: |
        mkdir -p ~/.emacs.d
        cp ./init.el ~/.emacs.d/init.el

    - name: Clone emacs-moose-mode locally
      run: |
        mkdir -p ~/.emacs.d/lisp
        git clone --depth 1 https://github.com/dylanjm/emacs-moose-mode.git ~/.emacs.d/lisp/emacs-moose-mode

    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: leotaku/elisp-check@master
      with:
        file: ~/.emacs.d/init.el
        ignore_warnings: ${{ matrix.ignore_warnings }}
